version: "3.8"
services:
  app:
    build:
      context: ./app
      dockerfile: ../build/app/Dockerfile
    tty: true
    volumes:
      - ./app:/app
      - app_modules:/app/node_modules
  web:
    image: nginx:1.25.4
    ports:
      - "3001:80"
    tty: true
    volumes:
      - ./build/web/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  app_modules:
