version: "3.8"
services:
  app:
    build:
      context: ./app
      dockerfile: ../build/app/Dockerfile
    ports:
      - "3001:3000"
    tty: true
    volumes:
      - ./app:/app
      - app_modules:/app/node_modules

volumes:
  app_modules:
